services:
  backend:
    build: .
    container_name: expense-tracker-backend
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  db:
    image: postgres:14
    container_name: expense-tracker-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: expense-tracker-redis
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data:
