# Generated by Django 5.0.4 on 2024-08-31 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_alter_savings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='saving',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='savings.savings'),
        ),
    ]
