# Generated by Django 5.0.4 on 2024-09-30 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_alter_payments_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='started_at',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
