# Generated by Django 5.0.4 on 2025-05-04 14:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportthread',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='support.supportmessage'),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='staff_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='user_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sent_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 5, 4, 14, 3, 20, 608339, tzinfo=datetime.timezone.utc)),
        ),
    ]
