# Generated by Django 5.0.4 on 2025-05-04 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportthread_last_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='sent_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
