# Generated by Django 5.0.4 on 2024-08-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.categories'),
        ),
    ]
