# Generated by Django 5.0.4 on 2025-03-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_budget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
