# Generated by Django 5.0.4 on 2025-03-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_budget_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='percentage',
        ),
    ]
