# Generated by Django 5.0.4 on 2025-04-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
